spring.application.name=ERP
server.port=${PORT:8080}
# Database URL
spring.datasource.url=jdbc:postgresql://localhost:5432/erp_managment

# Database credentials
spring.datasource.username=postgres
spring.datasource.password=2010

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate (JPA)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Show SQL (optional)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
